### PR TITLE
create test is_filetype_supported

### LINKED ISSUE #28: Unit test for checking supported file formats
We need to make sure this function: https://github.com/oliver-pham/silkie/blob/65024a5de14db1aae9fc22f01c74880835745523/silkie/utils.py#L27-L29

- return `True` if the file has one of the [supported file extensions](https://github.com/oliver-pham/silkie/blob/65024a5de14db1aae9fc22f01c74880835745523/silkie/definitions.py#L5).
- return `False` if the file extension is not supported, invalid file path, or a path to a directory
- error handling for "bad" values (e.g. empty string, `None`) _(this may need a fix)_

### PR DESCRIPTION
**Pull request by Yoda-Canada**
Fix #28
test file for issue #28

### CODE REVIEW

**Comment by oliver-pham** [comment]
Great work 🎉 , @Yoda-Canada! Just a small issue with the name of each test. I'd rather have something as verbose as `test_supported_windows_file_path` than `test_is_filetype_supported1`.

**Comment by Yoda-Canada** [comment]
I have changed all names, but there are three commits. I am confused how to merge them to one

**Comment by oliver-pham** [comment]
Sorry if I didn't make it clear enough, @Yoda-Canada. What I was trying to say is that you should name the test cases according to what it wants to test.
For example:
```python
def test_supported_windows_file_path6():
    file_path = "/Users/anonymous/Documents/test"
    assert is_filetype_supported(file_path) == False, "empty extension error"
```

`test_supported_windows_file_path6` doesn't explain what the test does. The test actually checks a Unix file path (`"/Users/anonymous/Documents/test"`) that has no extension. Therefore, it'd better to name it `test_empty_extension_unix_file_path`. I think it's good practice to name each test case descriptively so that it should give developers a clue about what the test case does.

**Comment by oliver-pham** [comment]
Don't worry about rebasing for now. I can help you with that from my end.

**Review by oliver-pham — APPROVED** [review]
Alright! Thanks a lot for your contribution 👏

**Comment by Yoda-Canada** [comment]
> Alright! Thanks a lot for your contribution 👏

please help me to merge all commits. I always have mistakes to do it. thx.

**Pull request merged**
