### PR TITLE
10 markdown support

### PR DESCRIPTION
**Pull request by ycechungAI**

### CODE REVIEW

**Comment by ycechungAI** [comment]
#10

**Comment by oliver-pham** [comment]
Some major changes I'd recommend for your PR @ycechungAI:
- Instead of passing the file extension down the functions, you can extract it from the file path. That'd make the interface of the functions cleaner.
- Try to refactor the `get_html_paragraphs_parsewithmd()` as much as possible. I think to avoid using a lot of if/elif statements, you can use a dictionary to store the Markdown syntax instead of hardcoded values.

Thanks for your contribution 🥳 !

**Comment by ycechungAI** [comment]
um not sure how i would shorten the if elsif statemetns because they are kind of different
also the "python silkie.py -i README.md -s blueprintmd/new.css" doesnt output anything

**Comment by oliver-pham** [comment]
> um not sure how i would shorten the if elsif statemetns because they are kind of different
> also the "python silkie.py -i README.md -s blueprintmd/new.css" doesnt output anything

1. Since the logic inside each `if/else if` block is repeated, can you write a function that accepts Markdown element and its corresponding HTML element as function parameters? Then, you can use a dictionary to store all Markdown elements with their corresponding HTML elements to pass to that function.
2. The stylesheet feature is broken on your side because you pass the wrong parameters to the `generate_static_file()` function (check my code review)

**Comment by ycechungAI** [comment]
not sure how to refactor the if statements a little guidance would be helpful

**Comment by ycechungAI** [comment]
#11

**Pull request closed without merging**
